Traceback (most recent call last):
  File "/home/scott/jamesd/FFRParam/runFFRParam.py", line 32, in <module>
    os.makedirs(dir)
  File "/util/opt/anaconda3/2.0/envs/py35/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'runFFRParam_1p1_1p1'
